### ISSUE TITLE
Problems with access and data loading

### ISSUE THREAD

**Issue by LauraKr** [simonbromberg/googlefitbit#2]
Dear Simon,
I am a psychiatrist with only very small knowledge in programming. For a study I want to get the intraday sleep data out of the Fitbit One. I requested a partner API as recommend and got access. I was very lucky to find your intraday.gs, but after several days of trying and getting forward slowly, I now hit a wall, I cannot go through on my own due to my lack of knowledge at these things. I would really appreciate your help.
My problem start and step 6: 

> In your spreadsheet, click Authorize from the Fitbit menu and a sidebar will show up. Click the link in the >sidebar, log in to Fitbit in the new window, authorize the application, and then close the tab when it says >"Success you can close this tab"

I do not find a authorize command, but I clicked the showSidebar, then I can authorize. In the new window Fitbit asks me to accept or deny the ability to access the certain data in my account. However, when I click accept, the message "Success you can close this tab" does not appear, but a blank page. When I then go to step 7:

> Back in your spreadhseet, hit Sync, and after a few moments the data should load in.
> There is no Sync command but a refreshTimeSeries command. However when I click it, a message appears saying: "Access not granted or expired". I thought the Fitbit API team provided access to me...

If you have an ideas to my problem I would really appreciate your input. Coffee is for sure ;-)

Best wishes,
Laura

**Comment by simonbromberg** [comment]
Should not be showing up as "showSidebar" or "refreshTimeSeries". Are you sure you're using the right script?

Also, as far as I know intraday data does not include sleep data. https://wiki.fitbit.com/display/API/API-Get-Intraday-Time-Series

**Comment by LauraKr** [comment]
Thank you for your answer. I guess it is the right script "intraday.gs". I noticed that in line 21 to 41 the names "showSidebar" for authorize and "refreshTimeSeries" for Download data is coded. As I am a complete newbie can am no able to find out, if there is already a problem because I can not see Authorize and Download data, but instead  "showSidebar" and "refreshTimeSeries"...
As far as I did understand intraday data include sleep data...
Greetings, 
Laura

**Comment by simonbromberg** [comment]
The "Fitbit" menu should appear at the top of the spreadsheet (not in the script editor) a couple seconds after the spreadsheet loads. You would need to refresh the spreadsheet after the first time you copy the script in. I have updated the readme to make this more clear.

**Comment by LauraKr** [comment]
You are right, that was my fault, and I guess, that is indeed very embarrassing! You did the work in the script...I did not see the Fitbit menu, but now I do. 
Unfortunately the whole thing is not solved completely yet:
In the new window after the authorize command Fitbit asks me to accept or deny the ability to access the certain data in my account. However, when I click accept, the message "Success you can close this tab" does not appear, but a blank page. Nothing else happens.
Back in the spreadhseet, I hit Download data a message appears saying: "Access not granted or expired". I mailed now to the Fitbit API team asking if there is a problem with my access.
I am not sure, if the Access problem might occurs because I did not authorize properly and did not get the message of successful authorization.
I would appreciate your feedback on this again.
I want to thank you, unfortunately coffee ist going to be difficult, because Square cash obviously does not work with credit cards from Germany...Maybe your are using paypal..?

Best wishes,
Laura

**Comment by simonbromberg** [comment]
Make sure you went through the setup step and the credentials / callback URI are correct, although I don't think you would get as far as you did if you didn't have that done properly.

Make sure you didn't accidentally leave out or modify any portion of the original script

Could also try doing it in incognito mode / private browsing

re: thank you, If you really want you can message me through my website. Or donate some money to a relevant charity.

**Comment by LauraKr** [comment]
Dear Simon,
now it works!! Yeah!! Thank you again!
And of course you was right, sleep data are not provided, but anyway, I went through :-)
Best wishes,
Laura
